---
abstract: 'Plack::Middleware::Static with open file cache'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  File::Copy: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Static-OpenFileCache
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Middleware::Static::OpenFileCache:
    file: lib/Plack/Middleware/Static/OpenFileCache.pm
    version: 0.02
  Plack::Middleware::Static::OpenFileCache::IOWithPath:
    file: lib/Plack/Middleware/Static/OpenFileCache.pm
requires:
  Cache::LRU::WithExpires: 0.03
  Plack: 1.0029
  perl: 5.008005
resources:
  bugtracker: https://github.com/kazeburo/Plack-Middleware-Static-OpenFileCache/issues
  homepage: https://github.com/kazeburo/Plack-Middleware-Static-OpenFileCache
  repository: git://github.com/kazeburo/Plack-Middleware-Static-OpenFileCache.git
version: 0.02
